### ISSUE TITLE
cuda run time error

### ISSUE THREAD

**Issue by CassieMai** [mapleneverfade/pytorch-semantic-segmentation#3]
Hello, @mapleneverfade, I run your code with my own dataset, and I have this error. Before I changed to use my own data, the code ran well. Do you have any idea?

````
pytorch-semantic-segmentation$ CUDA_VISIBLE_DEVICES=0 python3 train.py --datadir ./data/ --savedir ./save_models/ --model segnet

------------ Options -------------
batch_size: 1
cuda: True
datadir: ./data/
epoch_save: 5
iouTrain: True
iouVal: True
lr: 0.0005
model: segnet
num_classes: 2
num_epochs: 15
num_workers: 4
pretrained: ./pre_trained/~~~.pth
resume: False
savedir: ./save_models/
state: None
steps_loss: 5
-------------- End ----------------
========== TRAINING ===========
/home/user/.local/lib/python3.5/site-packages/torch/nn/modules/loss.py:198: 
UserWarning: NLLLoss2d has been deprecated. Please use NLLLoss instead as a drop-in replacement and see http://pytorch.org/docs/master/nn.html#torch.nn.NLLLoss for more details.
  warnings.warn("NLLLoss2d has been deprecated. "
----- TRAINING - EPOCH 1 -----
LEARNING RATE:  0.0005
/home/user/.local/lib/python3.5/site-packages/torch/nn/functional.py:1749: 
UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/user/.local/lib/python3.5/site-packages/torch/nn/functional.py:1820: 
UserWarning: nn.functional.upsample_bilinear is deprecated. Use nn.functional.upsample instead.
  warnings.warn("nn.functional.upsample_bilinear is deprecated. Use nn.functional.upsample instead.")
train.py:100: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  epoch_loss.append(loss.data[0])
loss: 4.302797794342041 (epoch: 1, step: 0) // Avg time/img: 0.0428 s
THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu line=265 error=59 : device-side assert triggered

Traceback (most recent call last):
  File "train.py", line 155, in <module>
    main(parser)
  File "train.py", line 149, in main
    model = train(args,model)
  File "train.py", line 98, in train
    optimizer.step()
  File "/home/user/.local/lib/python3.5/site-packages/torch/optim/adam.py", line 89, in step
    grad = grad.add(group['weight_decay'], p.data)

RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:265
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [0,0,0], thread: [866,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [0,0,0], thread: [867,0,0] Assertion `t >= 0 && t < n_classes` failed.
```
`

**Comment by xiaoyufenfei** [comment]
Hello @CassieMai ! How do you solve this problem, and I have the same problem? Thank you
